### ISSUE TITLE
Some doubts about the wire labels

### ISSUE THREAD

**Issue by zipotron** [reostat/usb_displ#1]
Hello, I don't know if I am writing in the right place, but couldn't find other way. I am trying to run your project in a AlhambraII board, and I am lost in the FTDI pin names. What is FTDI_GPIOL0? also, I guess FTDI_CS is a chip select, do we need this or can I assign to 1?
I just identify useful FTDI_DO and FTDI_SK (and maybe this is the reason that is not working...)
Also, what is pmoden?
Thank you very much!

**Comment by reostat** [comment]
Hi @zipotron 

I renamed pins because I'm using FT2232H chip in MPSSE mode and the regular pin naming doesn't make much sense there. Basically, FTDI_GPIOL0 is DTRn and FTDI_CS is CTSn ; you can find pin names and their assignments in `fpga_code/icestick.pcf` file. You may also want to consult with [iCEStick user manual](http://www.latticesemi.com/view_document?document_id=50701) to understand the schematics.

FTDI_CS is indeed chip select and is wired to SSD 1331 CS pin. However, you cannot just assign it to 1, it has to be properly driven for sending commands/data to OLED display (you can find relevant code in my`lib_ssd1331` driver repository). You may also want to consult with SSD 1331 datasheet to understand how commands/data are being sent into display.

`pmoden` is wired to another OLED control pin, EN, and it plays role in display initialization procedure.

**Comment by zipotron** [comment]
Hi! Thanks a lot! I have the display on now, but is just showing lines and random points, something in missing seams (maybe in the C part...). Just the last question, is regarding 'pmoden', where to wire it? If I underestood good, no need to wire if there is only one display? anyway in the display is not place left for 'pmoden'.
Other thing, I didn't fork your repo because I wanted to have the code without git submodules, but I mention you and and the link to your repo in the README. Also, the C part, I had to modify some lines for compile in my side, Do you want a MR?
Thanks again!

**Comment by reostat** [comment]
I was using [Digilent PMOD OLED Display](https://reference.digilentinc.com/reference/pmod/pmodoledrgb/reference-manual); if you scroll down to "Pinout Description Table" you'll see that in this display version `PMODEN` is a `Vdd` pin, so basically I just pull it high right after reset (please disregard my previous comment that it's being used in initialization procedure; I confused it with `Vcc` pin). There are other hardware versions of this display that don't use PMOD interface and don't have this pin, e.g. [this one](https://www.amazon.com/dp/B0711RKXB5/). I'm not sure how the startup procedure should be handled for them; you may want to check [this code for ulx3s board](https://github.com/emard/ulx3s-misc/tree/master/examples/oled/hdl) that uses similar display.

It's totally fine to use my code with or without forking and with or without mentioning, although I surely appreciate the latter :) As for the MR, I haven't touched this code for more than 2 years so I'll have a really hard time verifying it. How about this: I'll just put a link to your repository into my README so whoever came across it would know that there's a port for another board.

Good luck with figuring out how to make it work, this is the most fun part!

**Comment by zipotron** [comment]
A lot of useful information, I will check it!
About the MR, completely understandable, yes, a link in the README is perfect.
Thanks a lot for the help! Now is time to have fun!
